### ISSUE TITLE
Retrieval of per-project saved attribute count can be slow on large redcap systems

### ISSUE THREAD

**Issue by pbchase** [ctsit/project_ownership#19]
The retrieval of the per-project saved attribute count can be slow on large redcap systems. In this, [query of the redcap_data table](https://github.com/ctsit/project_ownership/blob/04ca915c69f2e07c441d2b5654a85d4e214df143/ExternalModule.php#L133) the where clause uses project_id which is not indexed. We ran into this in the [report_production_candidates](https://github.com/ctsit/report_production_candidates) module.  To address it we created a table, redcap_projects_stats to store saved attribute count data that is refreshed nightly via cron job. 

I suggest we add an optimization where we say something like

```
if exists redcap_project_stats:
  count = output_of("select saved_attribute_count from redcap_project_stats where project_id = $project_id")
else
  count = the current method
```

This would allow us to run faster without having an explicit dependency.  We could document how to use [report_production_candidates](https://github.com/ctsit/report_production_candidates) to get a performance boost if the query speed is an issue.

**Comment by tbembersimeao** [comment]
Fixed on 2.0.0 release.
