### ISSUE TITLE
Customers are leaving PI info blank when creating new research projects

### ISSUE THREAD

**Issue by pbchase** [ctsit/project_ownership#20]
Our reports indicate our customers are leaving PI info blank when creating new research projects. We hesitate to require the the PI fields be filled.  Could we instead influence their behavior by asking for the ownership info _first_ and using that to autofill blank PI info?  

![move_project_ownership_section_to_top](https://user-images.githubusercontent.com/3356493/39581985-d5a2bb60-4eba-11e8-9197-ab1beca60849.png)

We do a good job of autofilling ownership info from available data. We could leverage that to allow our customers a faster data entry option when the ownership and PI match as they generally should. If we ask for the ownership info first and use it to autofill the PI info the customer could be done in as little as one click, i.e. by clicking "I am the owner". The redcap username field could get them done with one text entry field. This is much faster than the current method. 

In the worst case scenario, the ownership info autofills the PI wrong and the customer has to rekey the PI info. That is no worse than what happens today, yet in a sense it is better. The wrong data in the PI fields might cue the customer to do the data entry in the PI fields when previously that would have been skipped. There is some mild annoyance here, but that might be unavoidable if we want the fields filled in.

**Comment by tbembersimeao** [comment]
@pbchase do you think turning PI fields required might solve the issue?

**Comment by pbchase** [comment]
Fixed by PR #22
