### ISSUE TITLE
"Owner user account" search returns no results.  Ever.

### ISSUE THREAD

**Issue by pbchase** [ctsit/project_ownership#36]
The search field `Owner user account` search returns no results when searches for name or email fragments in the `Owner name` and `Owner email` fields _do_ return results.

With no search we see these results:

![Screen_Shot_2019-04-17_at_5_09_23_PM](https://user-images.githubusercontent.com/3356493/56321594-0e255780-6135-11e9-9895-86e9c1a66d75.png)

With a last name we see this

![Screen_Shot_2019-04-17_at_5_13_40_PM](https://user-images.githubusercontent.com/3356493/56321522-dfa77c80-6134-11e9-9a9d-01be0cf4bb36.png)

Searching with the correct `Owner user account`, we see nothing:

![Screen_Shot_2019-04-17_at_5_09_06_PM](https://user-images.githubusercontent.com/3356493/56321537-e7ffb780-6134-11e9-97bb-293cde6627b6.png)

**Comment by ChemiKyle** [comment]
This is related to issue #40 and is "addressed" in PR #41 by removing the column entirely. Commenting here to mark it for closing in the event of merging the PR.

**Comment by mbentz-uf** [comment]
Closing issue

> This is related to issue #40 and is "addressed" in PR #41 by removing the column entirely. Commenting here to mark it for closing in the event of merging the PR.
