### ISSUE TITLE
PI setting not sticking

### ISSUE THREAD

**Issue by pbchase** [ctsit/project_ownership#38]
An end-user reports:

```
For some reason, every time I save my PI's name and email, the system automatically replaces it with mine when I check again.
```

Jerri says she has seen this as well.

**Comment by pbchase** [comment]
@tlstoffs, this is your issue. ;-)

**Comment by ChemiKyle** [comment]
I was able to recreate this in version 9.1.1. The PI changes to whoever is listed as the project owner, but only if tied to an account, i.e. manually filling in information for the project owner does not cause an overwrite of the PI information.

**Comment by ChemiKyle** [comment]
The bug behavior is fairly strange and inconsistent. With Project Ownership data tied to an account, altering the PI information and hitting save will occasionally work. Clicking on the project setup tab again before navigating away from the page and back will raise the probability that the fields display the information as input by the user, but will sometimes overwrite. If the information did _not_ overwrite, then a normal page refresh will overwrite it, but a hard refresh will bring it back.

None of this affects the middle initial, however, if the project owner does not have a middle initial set, the field displayed will always show what was input by the user.

https://github.com/ctsit/project_ownership/blob/3245eee8fd2b04844b8d9a8761574764d07d26bb/js/owner-fieldset.js#L74-L79

It seems backend and frontend are competing to alter the field, the inconsistency is likely tied to conditions being favorable to PHP or Javascript.
