### ISSUE TITLE
Remove Several Fields from Project Ownership List Page

### ISSUE THREAD

**Issue by ChemiKyle** [ctsit/project_ownership#40]
Many fields are considered clutter and should be removed or combined.

1. Record Count is inaccurate and is no longer useful, should be removed
2. Owner User Account is not searchable as expected, the column should be removed and the user account page will be hotlinked in Owner Name.
3. Owner Email is clickable, but the `mailto` destination is blank, this should be changed to function as expected.

**Comment by pbchase** [comment]
addressed in PR #41
