### ISSUE TITLE
Display errors with REDCap 9.3.x

### ISSUE THREAD

**Issue by pbchase** [ctsit/project_ownership#42]
Project ownership's list of projects has a display error under REDCap 9.3.x. The content of pull-down menus is displayed to the right of the selector. It's visually obtrusive and hard to use. It's unclear if this bug is in project_ownership or redcap_entity [https://github.com/ctsit/redcap_entity](https://github.com/ctsit/redcap_entity). 

@ChemiKyle should be able to produce screenshots and provide precise version numbers for the REDCap and modules involved.

**Comment by ChemiKyle** [comment]
Here is a screenshot of the error appearing in the Project Ownership page:

![image](https://user-images.githubusercontent.com/20332546/68677587-5b7e7180-052a-11ea-9d9d-c46013bf8d68.png)

Versions of REDCap and modules are listed below.

|Software|Version|
|:----|----:|
|REDCap|9.3.6|
Project Ownership|2.0.3|
|REDCap Entity|2.3.0|

The graphical error also appears using the current develop branches of both modules at the time of this comment. I believe the bug may be in Entity.

**Comment by ChemiKyle** [comment]
Moved issue to [REDCap Entity](https://github.com/ctsit/redcap_entity/issues/12) which caused the bug.
