### ISSUE TITLE
Billable flag is not editable

### ISSUE THREAD

**Issue by pbchase** [ctsit/project_ownership#52]
The billable flag on the project ownership page should be editable. I'm not sure where the best place for that is. This flag should only be settable by people with superuser/admin rights

**Comment by ChemiKyle** [comment]
How do you envision this would be implemented? Here's a mockup of it in the Control Center panel:

![image](https://user-images.githubusercontent.com/20332546/187757759-8286eb10-17a6-4859-a117-807d0efa002b.png)

This might require some hacking on Entity itself.

**Comment by pbchase** [comment]
Addressed by PR #56
